Add changes to feature branch
Sohail006/My-Micriverse-Hello-Project pull request #1
Opened 2022-03-22 14:21 UTC by Sohail006

Changes made in my project for review

2022-03-22 17:18 UTC, ShadyShawkat requested changes
## Hi @Sohail006, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Please make sure to give your pull request a descriptive title. This will make it more professional.
- [ ]  Kindly make sure to have a meaningful description in your pull request summarizing the features you implemented in it.
- [ ] Please be sure to remove the unwanted parts from your `readme.md` file. This helps making it more professional.
- [ ] Please edit the 'Getting started' section in your `readme.md` file to contain information on ho to set up the project locally.
- [ ] _Check the comments under the review for more changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] [OPTIONAL] Kindly make sure to give your branch a descriptive name in the future. As an example, "Set up project" or "Add homepage" would look more professional. (_**Don't create a new pull request or branch for this project's re-review**_)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 17:18 UTC, ShadyShawkat commented on .gitignore
> +test.md
- [x] Kindly add `node_modules` to your `.gitignore` file.

2022-03-23 14:05 UTC, Sohail006 commented on .gitignore
> +test.md
I have added node_modules to .gitignore file

2022-03-23 15:37 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi @Sohail006, 

Good job in making the changes. Keep rocking 💪 
Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 16:45 UTC, merged